### ISSUE TITLE
Indexing issue in perturbProgram

### ISSUE THREAD

**Issue by genos** [bollu/blaze#1]
First off, thanks for making this! I found it extremely informative, and I thoroughly enjoyed reading the notebook and code.

One small issue: I think you might have an indexing problem in `perturbProgram`, specifically in the definition of `ix'`. As it stands, you have

```haskell
ix' <- (ix +) <$> randint (0, length progInsts - 1)
```

This means that `ix'` could be larger than `length progInsts - 1`, since you're adding `ix` to it. While this doesn't result in an error due to how `drop` is defined (`drop 10 [1..3] = []`), it will mean that you're biased towards dropping the _entire_ list after `ix`, rather than just a portion of it. I think `ix'` should be defined as

```haskell
ix' <- randInt (ix, length progInsts - 1)
```

instead, which would ensure that it's never larger than the length of the list.

Cheers, and thanks again!

**Comment by bollu** [comment]
Indeed, you're right :) Is there any chance you could send me a PR with the fix? ;) If not, I'll fix this over the weekend...

**Comment by genos** [comment]
Sure thing! See #2.
